version: '3.3'
services:
  web:
    user: "1000:1000"
    image: tubes-1:latest
    build: 
      dockerfile: Dockerfile
    ports:
      - 8008:80
    hostname: tubes-1-web
    env_file:
      - .env
    volumes:
      - ./src/app:/var/www/app
      - ./src/public:/var/www/html
      - ./src/migration:/var/www/migration
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    hostname: tubes-1-db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    restart: unless-stopped
    hostname: tubes-1-adminer
    ports:
      - 8080:8080
    depends_on:
      - db
networks:
  tubes-1-network:
    driver: bridge
